// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mikencoderx.Context;
using AppContext = Mikencoderx.Context.AppContext;

#nullable disable

namespace Mikencoderx.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mikencoderx.Models.Administradores", b =>
                {
                    b.Property<int>("PkAdministradores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkAdministradores"), 1L, 1);

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkAdministradores");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Mikencoderx.Models.Clientes", b =>
                {
                    b.Property<int>("PkCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkCliente"), 1L, 1);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Mikencoderx.Models.Lenguajes", b =>
                {
                    b.Property<int>("PkLenguajes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkLenguajes"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("int");

                    b.Property<string>("URLFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkLenguajes");

                    b.ToTable("Lenguajes");
                });

            modelBuilder.Entity("Mikencoderx.Models.Lista_PL", b =>
                {
                    b.Property<int>("pkLista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pkLista"), 1L, 1);

                    b.Property<int>("FkLenguajes")
                        .HasColumnType("int");

                    b.Property<int>("FkProgramadores")
                        .HasColumnType("int");

                    b.HasKey("pkLista");

                    b.HasIndex("FkLenguajes");

                    b.HasIndex("FkProgramadores");

                    b.ToTable("Lista_PL");
                });

            modelBuilder.Entity("Mikencoderx.Models.Membresias", b =>
                {
                    b.Property<int>("PkMembresias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkMembresias"), 1L, 1);

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkClientes")
                        .HasColumnType("int");

                    b.Property<int>("FkPlanes")
                        .HasColumnType("int");

                    b.Property<int>("FkProyecto")
                        .HasColumnType("int");

                    b.HasKey("PkMembresias");

                    b.HasIndex("FkClientes");

                    b.HasIndex("FkPlanes");

                    b.HasIndex("FkProyecto");

                    b.ToTable("Membresias");
                });

            modelBuilder.Entity("Mikencoderx.Models.Planes", b =>
                {
                    b.Property<int>("PkPlanes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkPlanes"), 1L, 1);

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dias")
                        .HasColumnType("int");

                    b.HasKey("PkPlanes");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("Mikencoderx.Models.Programadores", b =>
                {
                    b.Property<int>("PkPrgramadores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkPrgramadores"), 1L, 1);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descrpcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URLFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkPrgramadores");

                    b.ToTable("Programadores");
                });

            modelBuilder.Entity("Mikencoderx.Models.Proyectos", b =>
                {
                    b.Property<int>("PkProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkProyecto"), 1L, 1);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("FkProgramadores")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URLMaster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URLWeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkProyecto");

                    b.HasIndex("FkProgramadores");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Mikencoderx.Models.Registros", b =>
                {
                    b.Property<int>("PkRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkRegistro"), 1L, 1);

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkAdministrador")
                        .HasColumnType("int");

                    b.HasKey("PkRegistro");

                    b.HasIndex("FkAdministrador");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("Mikencoderx.Models.Lista_PL", b =>
                {
                    b.HasOne("Mikencoderx.Models.Lenguajes", "Lenguajes")
                        .WithMany()
                        .HasForeignKey("FkLenguajes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mikencoderx.Models.Programadores", "Programadores")
                        .WithMany()
                        .HasForeignKey("FkProgramadores")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lenguajes");

                    b.Navigation("Programadores");
                });

            modelBuilder.Entity("Mikencoderx.Models.Membresias", b =>
                {
                    b.HasOne("Mikencoderx.Models.Clientes", "Clientes")
                        .WithMany()
                        .HasForeignKey("FkClientes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mikencoderx.Models.Planes", "Planes")
                        .WithMany()
                        .HasForeignKey("FkPlanes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mikencoderx.Models.Proyectos", "Proyectos")
                        .WithMany()
                        .HasForeignKey("FkProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Planes");

                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("Mikencoderx.Models.Proyectos", b =>
                {
                    b.HasOne("Mikencoderx.Models.Programadores", "Programadores")
                        .WithMany()
                        .HasForeignKey("FkProgramadores")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programadores");
                });

            modelBuilder.Entity("Mikencoderx.Models.Registros", b =>
                {
                    b.HasOne("Mikencoderx.Models.Administradores", "Administradores")
                        .WithMany()
                        .HasForeignKey("FkAdministrador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administradores");
                });
#pragma warning restore 612, 618
        }
    }
}
